#!/home/ansible/gcp_ansible/bin/ansible-playbook
- name: Overview of ansible debug module
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Task for debug module messaging