#!/home/ansible/gcp_ansible/bin/ansible-playbook
- name: This will show the Use of Comparision Operators
  hosts: localhost
  gather_facts: false

  vars:
    x : 20
    y : 10
    z : 30
  
  tasks:
   - name: Operation for conditional statements
     debug:
       msg:
        - "Value of x : {{x}}"
        - "Value of y : {{y}}"

   - name: Operation for conditional statements I
     debug:
       msg:
        - "x is smaller than y"
     when: x < y

   - name: Operation for conditional statements II
     debug:
       msg:
        - "x is greater than y"
     when: x > y

   - name: Operation for conditional statements III
     debug:
       msg:
        - "z is smaller than y"
     when: z < y

   - name: Operation for conditional statements IV
     debug:
       msg:
        - "z is Greater than y"
     when: z > y