#!/home/ansible/gcp_ansible/bin/ansible-playbook
- name: New Playbook attached
  hosts: localhost
  gather_facts: false

  tasks:
   - name: play 2 - Task 1
     debug: 
      msg: "Play 2 - Task 1"
   - include: task1.yml