#!/home/ansible/gcp_ansible/bin/ansible-playbook
- name: Installing Webserver
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
    - name: Ensure Apache is at latest version
      yum:
        name: httpd
        state: latest
    - name: Ensure apache is up and running
      service:
        name: httpd
        state: started