#!/home/ansible/gcp_ansible/bin/ansible-playbook
- name: Introduction to Register and set-facts.
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  tasks:
   - name: Retrive Shell version
     shell: "bash --version"
     register: bash_ver
   
   - set_fact:
       bash_version: "{{ bash_ver.stdout_lines[0].split()[3] }}"

   - debug:
      var: bash_version