#!/home/ansible/gcp_ansible/bin/ansible-playbook
- name: Overview of ansible debug module
  hosts: all
  remote_user: ec2-user
  become: 'yes'
  become_user: root

  vars:
    xyz: Hello this is xyz1
    packages: ['wget','unzip','curl','vim']
    cities:
    - New York
    - London
    - Tokyo
    - Dubai
    web_server:  {'Linux': 'httpd', 'Unix': 'apache2'}


  tasks:
    - name: This is data collection
      debug: 
        var: xyz
    
    - name: Geting sequence data collection F 1
      debug: 
        var: packages
    
    - name: Geting sequence data collection F 2
      debug: 
        var: cities

    - name: Geting mapped data collection F 2
      debug: 
        var: web_server